# syntax=docker/dockerfile:1

FROM node:20-alpine AS build
WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG VITE_APP_NAME=Edgeonix
ARG VITE_APP_ENV=production
ARG VITE_ENABLE_APP_LOGS=false
ARG VITE_API_TIMEOUT_MS=20000
ARG VITE_AUTH_DEVICE_ID=edgeonix-erp-ui
ARG VITE_SERVICE_AUTH_URL=
ARG VITE_SERVICE_PLATFORM_URL=
ARG VITE_SERVICE_CATALOG_URL=
ARG VITE_SERVICE_INVENTORY_URL=
ARG VITE_SERVICE_SALES_URL=
ARG VITE_SERVICE_BILLING_URL=
ARG VITE_SERVICE_PAYMENTS_URL=
ARG VITE_SERVICE_INVOICES_URL=

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_APP_ENV=$VITE_APP_ENV
ENV VITE_ENABLE_APP_LOGS=$VITE_ENABLE_APP_LOGS
ENV VITE_API_TIMEOUT_MS=$VITE_API_TIMEOUT_MS
ENV VITE_AUTH_DEVICE_ID=$VITE_AUTH_DEVICE_ID
ENV VITE_SERVICE_AUTH_URL=$VITE_SERVICE_AUTH_URL
ENV VITE_SERVICE_PLATFORM_URL=$VITE_SERVICE_PLATFORM_URL
ENV VITE_SERVICE_CATALOG_URL=$VITE_SERVICE_CATALOG_URL
ENV VITE_SERVICE_INVENTORY_URL=$VITE_SERVICE_INVENTORY_URL
ENV VITE_SERVICE_SALES_URL=$VITE_SERVICE_SALES_URL
ENV VITE_SERVICE_BILLING_URL=$VITE_SERVICE_BILLING_URL
ENV VITE_SERVICE_PAYMENTS_URL=$VITE_SERVICE_PAYMENTS_URL
ENV VITE_SERVICE_INVOICES_URL=$VITE_SERVICE_INVOICES_URL

RUN pnpm build

FROM nginx:1.27-alpine AS runtime

ENV AUTH_UPSTREAM=host.docker.internal:8080
ENV PLATFORM_UPSTREAM=host.docker.internal:8081
ENV CATALOG_UPSTREAM=host.docker.internal:8081
ENV INVENTORY_UPSTREAM=host.docker.internal:8082
ENV SALES_UPSTREAM=host.docker.internal:8083
ENV BILLING_UPSTREAM=host.docker.internal:8084
ENV PAYMENTS_UPSTREAM=host.docker.internal:8085
ENV INVOICES_UPSTREAM=host.docker.internal:8086

COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
